version: "3.6"
services:
  app:
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    container_name: gbpaymentapi
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    ports:
      - "8080:8080"
    networks:
      - network
networks:
  network:
    driver: bridge
    name: spring
    external: true
